[localhost]
localhost ansible_connection=local

; local group vars
[localhost:vars]
name="kumar"
age=20
city="rajasthan"

[mongodb]
mongodb.yokshithkumar.shop

[catalogue]
catalogue.yokshithkumar.shop

[user]
user.yokshithkumar.shop

[frontend]
frontend.yokshithkumar.shop
