- name: print message like echo in shell
  hosts: localhost #for any specific servers
  connection: localhost
  tasks:
    - name: print message
      debug:      #if we not any arguments it'll print Hellow World!
        msg: "Hello Ansible!"
      